name: rubber
description: Rubber is an elastic bottomsheet widget with the customizable material spring animation.
version: 0.1.7
author: Mattia Crovero <mcrovero@gmail.com>
homepage: https://github.com/mcrovero/rubber

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
