name: rubber
description: An elastic material bottomsheet implementation
version: 0.1.2
author: Mattia Crovero <mcrovero@gmail.com>
homepage: https://github.com/mcrovero/rubber

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
